[package]
name = "zbx_sender"
version = "0.2.3"
authors = ["Alexander Andreev <andreevlex.as@gmail.com>"]
description = "Implementation of Zabbix Sender Client."
homepage = "https://github.com/ava57r/zbx-sender-rs"
repository = "https://github.com/ava57r/zbx-sender-rs"
documentation = "https://docs.rs/zbx_sender"
keywords = ["zabbix", "zabbix-sender", "zabbix-protocol"]
readme = "README.md"
license = "MIT"
edition = "2018"

[dependencies]
serde  = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1.5"
lazy_static = "1.4"
byteorder = "1.4"
failure = "0.1.8"
