[package]
name = "zbx_sender"
version = "0.1.0"
authors = ["Alexander Andreev <andreevlex.as@gmail.com>"]

[dependencies]
serde = "1.0.37"
serde_json = "1.0.13"
serde_derive = "1.0.37"

byteorder = "1.2.2"
failure = "0.1.1"
